export const hackathons = [
  {
    donation_current: {
      food: 100,
      prize: 200,
      swag: 50,
      thank_you: "John, Sarah, Michael",
    },
    donation_goals: { food: 1500, prize: 1200, swag: 400 },
    end_date: "2023-06-30",
    id: "a1234xyz56",
    image_url: "",
    links: [
      {
        color: "secondary",
        link: "https://example.com",
        name: "DevPost",
        open_new: "False",
        size: "large",
        variant: "contained",
      },
      {
        color: "primary",
        link: "https://www.paypal.com/donate/?hosted_button_id=123456789",
        name: "Donate",
        open_new: "false",
        size: "large",
        variant: "contained",
      },
    ],
    location: "New York, NY",
    nonprofits: [
      {
        id: "np001",
        name: "Charity for Children",
        problem_statements: "",
      },
    ],
    start_date: "2023-06-25",
    teams: [],
    title: "Help us improve the lives of underprivileged children",
    type: "hackathon",
  },
  {
    donation_current: {
      food: 50,
      prize: 100,
      swag: 30,
      thank_you: "Anna, David, Karen",
    },
    donation_goals: {
      food: 500,
      prize: 800,
      swag: 200,
    },
    end_date: "2023-09-30",
    id: "b4567uvw89",
    image_url: "",
    links: [
      {
        color: "secondary",
        link: "https://example.com",
        name: "DevPost",
        open_new: "False",
        size: "large",
        variant: "contained",
      },
      {
        color: "primary",
        link: "https://www.paypal.com/donate/?hosted_button_id=987654321",
        name: "Donate",
        open_new: "false",
        size: "large",
        variant: "contained",
      },
    ],
    location: "San Francisco, CA",
    nonprofits: [
      {
        id: "np002",
        name: "Environmental Conservation Society",
        problem_statements: "",
      },
    ],
    start_date: "2023-09-25",
    teams: [],
    title:
      "Join us in protecting the environment and preserving natural resources",
    type: "hackathon",
  },
  {
    donation_current: {
      food: 100,
      prize: 50,
      swag: 20,
      thank_you: "John, Mary, Bob",
    },
    donation_goals: {
      food: 500,
      prize: 300,
      swag: 100,
    },
    end_date: "2023-09-30",
    id: "7a5d5a74a7eb11eaa015d663bd873d93",
    image_url: "https://example.com/image.jpg",
    links: [
      {
        color: "secondary",
        link: "https://example.com/devpost",
        name: "DevPost",
        open_new: "False",
        size: "large",
        variant: "contained",
      },
      {
        color: "primary",
        link: "https://example.com/donate",
        name: "Donate",
        open_new: "false",
        size: "large",
        variant: "contained",
      },
    ],
    location: "New York, USA",
    nonprofits: [
      {
        id: "8b03d9c2a7eb11ea9c4dd663bd873d93",
        name: "Charity Organization Inc.",
        problem_statements: "How can we help homeless people?",
      },
    ],
    start_date: "2023-09-01",
    teams: [],
    title: "Hacking for Good: Solving the Challenges of Homelessness",
    type: "hackathon",
  },
  {
    donation_current: {
      food: 300,
      prize: 200,
      swag: 80,
      thank_you: "Alice, David, Emily",
    },
    donation_goals: {
      food: 1000,
      prize: 800,
      swag: 200,
    },
    end_date: "2023-11-30",
    id: "e7b75890a7eb11eab499d663bd873d93",
    image_url: "https://example.com/image2.jpg",
    links: [
      {
        color: "secondary",
        link: "https://example.com/devpost",
        name: "DevPost",
        open_new: "False",
        size: "large",
        variant: "contained",
      },
      {
        color: "primary",
        link: "https://example.com/donate",
        name: "Donate",
        open_new: "false",
        size: "large",
        variant: "contained",
      },
    ],
    location: "California, USA",
    nonprofits: [
      {
        id: "1a12e3b8a7ec11eab499d663bd873d93",
        name: "Environmental Protection Group",
        problem_statements: "How can we protect our planet?",
      },
    ],
    start_date: "2023-11-01",
    teams: [],
    title: "Hacking for the Environment: Saving Our Planet",
    type: "hackathon",
  },
  {
    donation_current: {
      food: 100,
      prize: 200,
      swag: 50,
      thank_you: "John, Sarah, Michael",
    },
    donation_goals: { food: 1500, prize: 1200, swag: 400 },
    end_date: "2023-06-30",
    id: "a1234xyz56",
    image_url: "",
    links: [
      {
        color: "secondary",
        link: "https://example.com",
        name: "DevPost",
        open_new: "False",
        size: "large",
        variant: "contained",
      },
      {
        color: "primary",
        link: "https://www.paypal.com/donate/?hosted_button_id=123456789",
        name: "Donate",
        open_new: "false",
        size: "large",
        variant: "contained",
      },
    ],
    location: "New York, NY",
    nonprofits: [
      {
        id: "np001",
        name: "Charity for Children",
        problem_statements: "",
      },
    ],
    start_date: "2023-06-25",
    teams: [],
    title: "Help us improve the lives of underprivileged children",
    type: "hackathon",
  },
];
