// ---------------------------------------------------------------------------
// Static option lists for the hacker application form.
//
// Kept at module scope (not inside the component) so they're allocated once
// per page load instead of on every render. This also lets MUI Autocomplete
// keep its internal memoization — passing the same `options` reference avoids
// re-filtering on every keystroke. If you re-introduce these inside a
// component you'll re-introduce the performance regression we fixed.
// ---------------------------------------------------------------------------

export const PARTICIPANT_TYPE_OPTIONS = [
  "Student",
  "Professional",
  "Educator",
  "Community Member",
  "Other",
];

export const EXPERIENCE_LEVEL_OPTIONS = [
  "First-time hacker",
  "Some hackathon experience (1-3 events)",
  "Experienced hacker (4+ events)",
];

export const PRIMARY_ROLE_OPTIONS = [
  "Software Development - Frontend",
  "Software Development - Backend",
  "Software Development - Mobile",
  "Software Development - Full Stack",
  "Design (UI/UX, Graphics)",
  "Data Science/Analytics",
  "Project Management",
  "Business Analysis",
  "Quality Assurance",
  "DevOps",
  "Other",
];

export const TECHNICAL_SKILLS_OPTIONS = {
  "Programming Languages": [
    "JavaScript/TypeScript",
    "Python",
    "Java",
    "C#/.NET",
    "Ruby",
    "PHP",
    "Go",
    "Swift",
    "Kotlin",
    "C/C++",
    "Rust",
    "Scala",
    "R",
    "Perl",
  ],
  "Frontend Development": [
    "React",
    "Angular",
    "Vue.js",
    "Next.js",
    "HTML/CSS",
    "Redux",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Web Components",
    "Svelte",
    "jQuery",
  ],
  "Backend Development": [
    "Node.js",
    "Express",
    "Django",
    "Flask",
    "Spring Boot",
    "Laravel",
    "ASP.NET",
    "Ruby on Rails",
    "FastAPI",
    "GraphQL",
    "RESTful APIs",
    "Serverless Architecture",
  ],
  "Mobile Development": [
    "React Native",
    "Flutter",
    "iOS Development",
    "Android Development",
    "Xamarin",
    "Ionic",
  ],
  "Database & Storage": [
    "SQL Databases",
    "PostgreSQL",
    "MySQL/MariaDB",
    "MongoDB",
    "NoSQL Databases",
    "Redis",
    "Elasticsearch",
    "DynamoDB",
    "Firebase",
    "ORM Tools",
  ],
  "DevOps & Cloud": [
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker",
    "Kubernetes",
    "CI/CD Pipelines",
    "GitHub Actions",
    "Jenkins",
    "Terraform",
    "Ansible",
  ],
  "Data Science & AI": [
    "Machine Learning",
    "AI/NLP",
    "Data Visualization",
    "TensorFlow",
    "PyTorch",
    "Computer Vision",
    "Pandas",
    "NumPy",
    "Big Data",
    "Statistical Analysis",
  ],
  "Design & UX": [
    "UI Design",
    "UX Research",
    "Graphic Design",
    "Figma",
    "Adobe XD",
    "Sketch",
    "Wireframing",
    "Prototyping",
  ],
  "Other Skills": [
    "Blockchain",
    "AR/VR",
    "IoT",
    "Game Development",
    "Cybersecurity",
    "Project Management",
    "Agile/Scrum",
    "Technical Writing",
    "Accessibility",
    "Other",
  ],
};

export const ALL_TECHNICAL_SKILLS =
  Object.values(TECHNICAL_SKILLS_OPTIONS).flat();

export const SOCIAL_CAUSES_OPTIONS = [
  "Education",
  "Healthcare",
  "Environment",
  "Economic Opportunity",
  "Community Development",
  "Accessibility/Inclusion",
  "Homelessness",
  "Food Security",
  "Mental Health",
  "Disaster Relief",
  "Animal Welfare",
  "Other",
];

export const WORKSHOP_OPTIONS = [
  "Pre-hackathon skill-building workshops",
  "During-event technical sessions",
  "Social impact design thinking",
  "Git/GitHub workflow",
  "Cloud deployment (AWS, GCP, Azure)",
  "UX/UI fundamentals",
  "Frontend (React, Next.js)",
  "Backend & API integration",
  "Database design",
  "Mobile development",
  "AI / Machine learning basics",
  "DevOps & CI/CD",
  "Cybersecurity basics",
  "Accessibility",
  "Working with nonprofits — scoping & requirements",
  "Pitch & demo coaching",
  "Fundraising & grants for tech projects",
  "Other",
];

export const ARIZONA_COUNTY_OPTIONS = [
  "Apache",
  "Cochise",
  "Coconino",
  "Gila",
  "Graham",
  "Greenlee",
  "La Paz",
  "Maricopa",
  "Mohave",
  "Navajo",
  "Pima",
  "Pinal",
  "Santa Cruz",
  "Yavapai",
  "Yuma",
];

// Country options — common first, then alphabetical. Stored value is the
// display name so legacy free-text records ("United States") line up.
export const COUNTRY_OPTIONS = [
  "United States",
  "Canada",
  "Mexico",
  "Argentina",
  "Australia",
  "Austria",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Chile",
  "China",
  "Colombia",
  "Czechia",
  "Denmark",
  "Egypt",
  "Finland",
  "France",
  "Germany",
  "Ghana",
  "Greece",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kenya",
  "Lebanon",
  "Malaysia",
  "Morocco",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Venezuela",
  "Vietnam",
  "Other",
];

// US state options — 50 states + DC. Used only when country === "United States".
export const US_STATE_OPTIONS = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const AGE_RANGE_OPTIONS = [
  "Under 18",
  "18-24",
  "25-34",
  "35-44",
  "45-54",
  "55+",
];

export const REFERRAL_SOURCE_OPTIONS = [
  "School/University",
  "Employer",
  "Social Media",
  "Friend/Colleague",
  "Previous Participant",
  "Nonprofit Organization",
  "Other",
];

export const TEAM_SIZE_OPTIONS = [
  "No preference",
  "2 people",
  "3 people",
  "4 people",
  "5 people",
  "I prefer to work alone even if that disqualifies me from winning a prize",
];
